In [41]:
import numpy as np
x,y=np.array([2.5,.5,2.2,1.9,3.1,2.3,2,1,1.5,1.1]),np.array([2.4,.7,2.9,2.2,3.,2.7,1.6,1.1,1.6,.9])
n=len(x)

In [42]:
x_mean,y_mean=np.mean(x),np.mean(y)
new_x,new_y=x-x_mean,y-y_mean
new_data=(new_x,new_y)

In [43]:
cov_x_x=np.sum((x-x_mean)**2)/(n-1)
cov_x_y=np.sum((x-x_mean)*(y-y_mean))/(n-1) #cove_x_y=cov_y_x(same)
cov_y_y=np.sum((y-y_mean)**2)/(n-1)
cov_x_x,cov_x_y,cov_y_y

(np.float64(0.6165555555555556),
 np.float64(0.6154444444444445),
 np.float64(0.7165555555555555))

In [44]:
cov_metrix=np.array([[cov_x_x,cov_x_y],[cov_x_y,cov_y_y]])
cov_metrix

array([[0.61655556, 0.61544444],
       [0.61544444, 0.71655556]])

In [45]:
eigenvalues,eigenvectors=np.linalg.eig(cov_metrix)
eigenvalues,eigenvectors

(array([0.0490834 , 1.28402771]),
 array([[-0.73517866, -0.6778734 ],
        [ 0.6778734 , -0.73517866]]))

In [46]:
if eigenvalues[0]>eigenvalues[1]:
  feature_vector=eigenvectors[0]
else:
  feature_vector=eigenvectors[1]
feature_vector

array([ 0.6778734 , -0.73517866])

In [47]:
Final_data=feature_vector@new_data
Final_data

array([ 0.1074951 ,  0.00155202, -0.46345624, -0.1521932 ,  0.07311195,
       -0.24863317,  0.35670133,  0.04641726,  0.01776463,  0.26124033])